version: '2.1'

services:
  automation:
    image: automation
    volumes:
      - /var/automation/config:/src/system/config
      - /var/automation/packages:/src/system/packages

  influxdb:
    image: influxdb
    environment:
      - 'INFLUXDB_DB=automation'
      - 'INFLUXDB_ADMIN_USER=admin'
      - 'INFLUXDB_ADMIN_PASSWORD=<ADMIN_PASSWORD>'
      - 'INFLUXDB_USER=automation'
      - 'INFLUXDB_USER_PASSWORD=<USER_PASSWORD>'
    ports:
      - '8086:8086'
    volumes:
      - influxdb

  #Optional service for grafana
  grafana:
    image: grafana/grafana
    environment:
      - 'GF_SECURITY_ADMIN_USER=admin'
      - 'GF_SECURITY_ADMIN_PASSWORD=<ADMIN_PASSWORD>'
    ports:
      - '3000:3000'
    volumes:
      - grafana
