system:
  influxdb:
    host: influxdb
    port: 8086
    user: automation
    pass: <USER_PASS>
    db_name: automation

nodes:
  unix_socket_node:
    node_type: default.unix_server
    config:
      socket_path: /var/automation/automation.sock

conditions:
  unix_server_conditions:
