system:
  influxdb:
    host: influxdb
    port: 8086
    user: automation
    pass: <USER_PASS>
    db_name: automation

nodes:
  pipe_node:
    node_type: default.pipe_node
    config:
      pipe_path: /var/automation/automation.pipe

conditions:
  pipe_conditions:
